[package]
name = "xtool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["full"] }
