[package]
name = "core_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-code = "3.0.0"
is-terminal = { version = "0.4.7", optional = true }

[features]
default = ["detect-tty", "detect-env", "std"]
detect-env = ["std"]
detect-tty = ["is-terminal", "std"]
std = ["alloc"]
alloc = []
