[package]
name = "crypto_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rust-crypto = "0.2.36"
rustc-hex = "2.1.0"
rustc-serialize = "0.3.24"
