#!/bin/bash

set -euo pipefail

function eprintln() {
  >&2 echo "$1"
}

eprintln "Formatting sources"
cargo fmt -- --check

eprintln "Linting sources"
cargo clippy --all-targets -- -D warnings

eprintln "Running tests (default)"
cargo test
eprintln "Running tests (alloc)"
cargo test --no-default-features --features alloc

eprintln "Building documentation"
cargo doc --no-deps

eprintln "Running examples (standard)"
cargo run --example xxx
